Added a dev shell
Added a dev shell instead of multiple packages cause packages shows the follow error ```❯ nix flake show
warning: Git tree '/home/roronoa/Documents/flakeadd/regolith-nix' is dirty
git+file:///home/roronoa/Documents/flakeadd/regolith-nix
└───packages
error: 'packages' is not an attribute set
```